version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: eCommerceService
    depends_on:
      - db
      - redis
    networks:
      - eCommerceService

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eCommerceService
      MYSQL_USER: schnee
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - eCommerceService

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - eCommerceService

networks:
  eCommerceService:


volumes:
  db_data: